version: "3.8"
  
services:

  web:
    env_file:
      - .env
    build: .
    command: python manage.py runserver 0.0.0.0:8040
    volumes:
      - .:/code
    ports:
      - "8040:8040"
    depends_on:
      - db

  db:
    image: postgis/postgis:12-3.0-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=party_pass#2022
      - POSTGRES_USER=party_user
      - POSTGRES_DB=db
    volumes:
      - "/opt/PartyRental/:/var/lib/postgresql/data"
